Repository WecoAI/weco-cli, pull requests merged in 2025-09, with the labels that each got.

#54 feat: implement credit-based billing system for CLI
  README.md
  examples/hello-kernel-world/optimize.py
  weco/api.py
  weco/auth.py
  weco/chatbot.py
  weco/cli.py
  weco/constants.py
  weco/credits.py
  weco/optimizer.py
  weco/utils.py
Labels: documentation, enhancement

#68 feat: Add resume functions
  README.md
  weco/api.py
  weco/cli.py
  weco/optimizer.py
Labels: enhancement

#70 Remove token usage info, remove best solution comment string, standardize API timeouts between codegen and status endpoints and improve code quality by reusing helper functions and simplifying code
  weco/api.py
  weco/constants.py
  weco/optimizer.py
  weco/panels.py
  weco/utils.py
Labels: enhancement

#75 Improve example docs
  examples/README.md
  examples/cuda/README.md
  examples/cuda/guide.md
  examples/prompt/README.md
  examples/triton/README.md
Labels: documentation
