Repository WecoAI/weco-cli, pull requests merged in 2025-05, with the labels that each got.

#12 feat: Implement CLI Liveness Tracking and Sync with Dev
  pyproject.toml
  weco/__init__.py
  weco/api.py
  weco/cli.py
  weco/panels.py
Labels: bug, enhancement

#17 Update CLI Args
  README.md
  examples/cuda/README.md
  examples/prompt/README.md
  examples/spaceship-titanic/README.md
  examples/triton/README.md
  pyproject.toml
  weco/cli.py
Labels: documentation, enhancement

#18 Add Colab CLI Walkthrough
  README.md
  examples/hello-kernel-world/colab_notebook_walkthrough.ipynb
Labels: documentation

#13 Feature/request cli stop
  weco/cli.py
Labels: enhancement

#16 Refactor/unify terms for clarity
  weco/api.py
  weco/cli.py
  weco/panels.py
Labels: documentation
