Repository WecoAI/weco-cli, pull requests merged in 2025-04, with the labels that each got.

#6 fix: Handle the case when there is no solution
  .github/workflows/release.yml
  pyproject.toml
  weco/__init__.py
  weco/cli.py
Labels: bug

#5 feat: Implement User Authentication and Session Ownership
  .github/workflows/release.yml
  .gitignore
  .repomixignore
  README.md
  weco/__init__.py
  weco/api.py
  weco/auth.py
  weco/cli.py
  weco/panels.py
Labels: bug, documentation, enhancement

#9 feat: Update model improvement example
  examples/spaceship-titanic/README.md
  examples/spaceship-titanic/baseline.py
  examples/spaceship-titanic/competition_description.md
  examples/spaceship-titanic/evaluate.py
  examples/spaceship-titanic/get_data.py
  examples/spaceship-titanic/optimize.py
  examples/spaceship-titanic/submit.py
  examples/spaceship-titanic/utils.py
Labels: enhancement
